# Generates keccak_core.h: one keccak-f[1600] implementation shared by nvcc (GPU) and clang (CPU tests).
RC = [0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000, 0x000000000000808B, 0x0000000080000001,
      0x8000000080008081, 0x8000000000008009, 0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
      0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003, 0x8000000000008002, 0x8000000000000080,
      0x000000000000800A, 0x800000008000000A, 0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008]
ROT = [0, 1, 62, 28, 27, 36, 44, 6, 55, 20, 3, 10, 43, 25, 39, 41, 45, 15, 21, 8, 18, 2, 61, 56, 14]
PI = [0] * 25
for x in range(5):
    for y in range(5):
        PI[x + 5 * y] = y + 5 * ((2 * x + 3 * y) % 5)
L = []
L.append("#define KECCAK_ROUND(RCV) do { \\")
for x in range(5):
    L.append(f"  c{x} = a{x} ^ a{x+5} ^ a{x+10} ^ a{x+15} ^ a{x+20}; \\")
for x in range(5):
    L.append(f"  d{x} = c{(x+4)%5} ^ KROTL(c{(x+1)%5}, 1); \\")
for i in range(25):
    L.append(f"  a{i} ^= d{i%5}; \\")
for i in range(25):
    src = f"a{i}" if ROT[i] == 0 else f"KROTL(a{i}, {ROT[i]})"
    L.append(f"  b{PI[i]} = {src}; \\")
for y in range(0, 25, 5):
    for x in range(5):
        a = x + y; b = (x + 1) % 5 + y; c = (x + 2) % 5 + y
        L.append(f"  a{a} = b{a} ^ ((~b{b}) & b{c}); \\")
L.append("  a0 ^= (RCV); \\")
L.append("} while (0)")
round_macro = "\n".join(L)
rounds = "\n".join(f"  KECCAK_ROUND(0x{rc:016X}ULL); \\" for rc in RC)
decl_a = ", ".join(f"a{i}" for i in range(25))
decl_b = ", ".join(f"b{i}" for i in range(25))
load = " ".join(f"a{i} = (S)[{i}];" for i in range(25))
store = " ".join(f"(S)[{i}] = a{i};" for i in range(25))
hdr = f"""// GENERATED by gen_core.py. keccak-f[1600] + the UNICRED digest layout, shared by miner.cu (nvcc) and the CPU build.
//
// digest = keccak256(abi.encode(DOMAIN, chainId, contract, challenge, miner, nonce)): 192 bytes = 2 keccak blocks.
// Block 1 (bytes 0..135) is constant per job -> midstate. Block 2 = bytes 136..191 + padding; the nonce's low
// 8 bytes (msg 184..191, big-endian) are lane 6 of block 2. Digest top 64 bits (most significant) = bswap64(lane 0).
#pragma once
#include <stdint.h>
#include <string.h>

#ifdef __CUDACC__
#define HD __host__ __device__ __forceinline__
#else
#define HD static inline
#endif

#define KROTL(x, n) (((x) << (n)) | ((x) >> (64 - (n))))

{round_macro}

// Declares the working variables a0..a24, b0..b24, c0..c4, d0..d4 in the current scope.
#define KECCAK_VARS uint64_t {decl_a}; uint64_t {decl_b}; uint64_t c0, c1, c2, c3, c4, d0, d1, d2, d3, d4
#define KECCAK_LOAD(S) do {{ {load} }} while (0)
#define KECCAK_STORE(S) do {{ {store} }} while (0)
// All 24 rounds on a0..a24.
#define KECCAK_F_VARS() do {{ \\
{rounds}
}} while (0)

HD uint64_t kbswap64(uint64_t x) {{
#if defined(__CUDA_ARCH__)
  uint32_t lo = (uint32_t)x, hi = (uint32_t)(x >> 32);
  return ((uint64_t)__byte_perm(lo, 0, 0x0123) << 32) | (uint64_t)__byte_perm(hi, 0, 0x0123);
#else
  return __builtin_bswap64(x);
#endif
}}

HD void keccakf(uint64_t s[25]) {{
  KECCAK_VARS;
  KECCAK_LOAD(s);
  KECCAK_F_VARS();
  KECCAK_STORE(s);
}}

HD uint64_t load_le64(const uint8_t *p) {{
  uint64_t v = 0;
  for (int k = 7; k >= 0; k--) v = (v << 8) | p[k];
  return v;
}}

// msg184: the first 184 message bytes (the nonce's low 8 bytes are supplied per attempt).
// base: state entering the block-2 permutation, with lane 6 excluding the nonce.
HD void unicred_prepare(const uint8_t *msg184, uint64_t base[25]) {{
  uint64_t s[25];
  for (int i = 0; i < 25; i++) s[i] = 0;
  for (int i = 0; i < 17; i++) s[i] ^= load_le64(msg184 + 8 * i);  // block 1: bytes 0..135
  keccakf(s);
  uint8_t blk[136];
  for (int i = 0; i < 136; i++) blk[i] = 0;
  for (int i = 0; i < 48; i++) blk[i] = msg184[136 + i];           // bytes 136..183; 184..191 = nonce low (zero here)
  blk[56] ^= 0x01;                                                  // keccak padding after 192 message bytes
  blk[135] ^= 0x80;
  for (int i = 0; i < 17; i++) s[i] ^= load_le64(blk + 8 * i);
  for (int i = 0; i < 25; i++) base[i] = s[i];
}}

// Top 64 bits (most significant) of the digest for nonce low word `nonce_low` (msg bytes 184..191 big-endian).
HD uint64_t unicred_top64(const uint64_t base[25], uint64_t nonce_low) {{
  uint64_t s[25];
  for (int i = 0; i < 25; i++) s[i] = base[i];
  s[6] ^= kbswap64(nonce_low);
  keccakf(s);
  return kbswap64(s[0]);
}}

// Full 32-byte digest (big-endian bytes, as the contract sees bytes32).
HD void unicred_digest(const uint64_t base[25], uint64_t nonce_low, uint8_t out[32]) {{
  uint64_t s[25];
  for (int i = 0; i < 25; i++) s[i] = base[i];
  s[6] ^= kbswap64(nonce_low);
  keccakf(s);
  for (int i = 0; i < 4; i++)
    for (int k = 0; k < 8; k++) out[8 * i + k] = (uint8_t)(s[i] >> (8 * k));
}}
"""
open("keccak_core.h", "w").write(hdr)
print("wrote keccak_core.h", len(hdr.splitlines()), "lines")
