// GENERATED by gen_core.py. Embedded Metal shader; do not edit.
#pragma once
static const char keccak_metal_source[] = R"metal(
#include <metal_stdlib>
using namespace metal;
typedef ulong uint64_t;
#define KROTL(x, n) (((x) << (n)) | ((x) >> (64 - (n))))

#define KECCAK_ROUND(RCV) do { \
  c0 = a0 ^ a5 ^ a10 ^ a15 ^ a20; \
  c1 = a1 ^ a6 ^ a11 ^ a16 ^ a21; \
  c2 = a2 ^ a7 ^ a12 ^ a17 ^ a22; \
  c3 = a3 ^ a8 ^ a13 ^ a18 ^ a23; \
  c4 = a4 ^ a9 ^ a14 ^ a19 ^ a24; \
  d0 = c4 ^ KROTL(c1, 1); \
  d1 = c0 ^ KROTL(c2, 1); \
  d2 = c1 ^ KROTL(c3, 1); \
  d3 = c2 ^ KROTL(c4, 1); \
  d4 = c3 ^ KROTL(c0, 1); \
  a0 ^= d0; \
  a1 ^= d1; \
  a2 ^= d2; \
  a3 ^= d3; \
  a4 ^= d4; \
  a5 ^= d0; \
  a6 ^= d1; \
  a7 ^= d2; \
  a8 ^= d3; \
  a9 ^= d4; \
  a10 ^= d0; \
  a11 ^= d1; \
  a12 ^= d2; \
  a13 ^= d3; \
  a14 ^= d4; \
  a15 ^= d0; \
  a16 ^= d1; \
  a17 ^= d2; \
  a18 ^= d3; \
  a19 ^= d4; \
  a20 ^= d0; \
  a21 ^= d1; \
  a22 ^= d2; \
  a23 ^= d3; \
  a24 ^= d4; \
  b0 = a0; \
  b10 = KROTL(a1, 1); \
  b20 = KROTL(a2, 62); \
  b5 = KROTL(a3, 28); \
  b15 = KROTL(a4, 27); \
  b16 = KROTL(a5, 36); \
  b1 = KROTL(a6, 44); \
  b11 = KROTL(a7, 6); \
  b21 = KROTL(a8, 55); \
  b6 = KROTL(a9, 20); \
  b7 = KROTL(a10, 3); \
  b17 = KROTL(a11, 10); \
  b2 = KROTL(a12, 43); \
  b12 = KROTL(a13, 25); \
  b22 = KROTL(a14, 39); \
  b23 = KROTL(a15, 41); \
  b8 = KROTL(a16, 45); \
  b18 = KROTL(a17, 15); \
  b3 = KROTL(a18, 21); \
  b13 = KROTL(a19, 8); \
  b14 = KROTL(a20, 18); \
  b24 = KROTL(a21, 2); \
  b9 = KROTL(a22, 61); \
  b19 = KROTL(a23, 56); \
  b4 = KROTL(a24, 14); \
  a0 = b0 ^ ((~b1) & b2); \
  a1 = b1 ^ ((~b2) & b3); \
  a2 = b2 ^ ((~b3) & b4); \
  a3 = b3 ^ ((~b4) & b0); \
  a4 = b4 ^ ((~b0) & b1); \
  a5 = b5 ^ ((~b6) & b7); \
  a6 = b6 ^ ((~b7) & b8); \
  a7 = b7 ^ ((~b8) & b9); \
  a8 = b8 ^ ((~b9) & b5); \
  a9 = b9 ^ ((~b5) & b6); \
  a10 = b10 ^ ((~b11) & b12); \
  a11 = b11 ^ ((~b12) & b13); \
  a12 = b12 ^ ((~b13) & b14); \
  a13 = b13 ^ ((~b14) & b10); \
  a14 = b14 ^ ((~b10) & b11); \
  a15 = b15 ^ ((~b16) & b17); \
  a16 = b16 ^ ((~b17) & b18); \
  a17 = b17 ^ ((~b18) & b19); \
  a18 = b18 ^ ((~b19) & b15); \
  a19 = b19 ^ ((~b15) & b16); \
  a20 = b20 ^ ((~b21) & b22); \
  a21 = b21 ^ ((~b22) & b23); \
  a22 = b22 ^ ((~b23) & b24); \
  a23 = b23 ^ ((~b24) & b20); \
  a24 = b24 ^ ((~b20) & b21); \
  a0 ^= (RCV); \
} while (0)

// Declares the working variables a0..a24, b0..b24, c0..c4, d0..d4 in the current scope.
#define KECCAK_VARS uint64_t a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24; uint64_t b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24; uint64_t c0, c1, c2, c3, c4, d0, d1, d2, d3, d4
#define KECCAK_LOAD(S) do { a0 = (S)[0]; a1 = (S)[1]; a2 = (S)[2]; a3 = (S)[3]; a4 = (S)[4]; a5 = (S)[5]; a6 = (S)[6]; a7 = (S)[7]; a8 = (S)[8]; a9 = (S)[9]; a10 = (S)[10]; a11 = (S)[11]; a12 = (S)[12]; a13 = (S)[13]; a14 = (S)[14]; a15 = (S)[15]; a16 = (S)[16]; a17 = (S)[17]; a18 = (S)[18]; a19 = (S)[19]; a20 = (S)[20]; a21 = (S)[21]; a22 = (S)[22]; a23 = (S)[23]; a24 = (S)[24]; } while (0)
#define KECCAK_STORE(S) do { (S)[0] = a0; (S)[1] = a1; (S)[2] = a2; (S)[3] = a3; (S)[4] = a4; (S)[5] = a5; (S)[6] = a6; (S)[7] = a7; (S)[8] = a8; (S)[9] = a9; (S)[10] = a10; (S)[11] = a11; (S)[12] = a12; (S)[13] = a13; (S)[14] = a14; (S)[15] = a15; (S)[16] = a16; (S)[17] = a17; (S)[18] = a18; (S)[19] = a19; (S)[20] = a20; (S)[21] = a21; (S)[22] = a22; (S)[23] = a23; (S)[24] = a24; } while (0)
// All 24 rounds on a0..a24.
#define KECCAK_F_VARS() do { \
  KECCAK_ROUND(0x0000000000000001UL); \
  KECCAK_ROUND(0x0000000000008082UL); \
  KECCAK_ROUND(0x800000000000808AUL); \
  KECCAK_ROUND(0x8000000080008000UL); \
  KECCAK_ROUND(0x000000000000808BUL); \
  KECCAK_ROUND(0x0000000080000001UL); \
  KECCAK_ROUND(0x8000000080008081UL); \
  KECCAK_ROUND(0x8000000000008009UL); \
  KECCAK_ROUND(0x000000000000008AUL); \
  KECCAK_ROUND(0x0000000000000088UL); \
  KECCAK_ROUND(0x0000000080008009UL); \
  KECCAK_ROUND(0x000000008000000AUL); \
  KECCAK_ROUND(0x000000008000808BUL); \
  KECCAK_ROUND(0x800000000000008BUL); \
  KECCAK_ROUND(0x8000000000008089UL); \
  KECCAK_ROUND(0x8000000000008003UL); \
  KECCAK_ROUND(0x8000000000008002UL); \
  KECCAK_ROUND(0x8000000000000080UL); \
  KECCAK_ROUND(0x000000000000800AUL); \
  KECCAK_ROUND(0x800000008000000AUL); \
  KECCAK_ROUND(0x8000000080008081UL); \
  KECCAK_ROUND(0x8000000000008080UL); \
  KECCAK_ROUND(0x0000000080000001UL); \
  KECCAK_ROUND(0x8000000080008008UL); \
} while (0)

inline ulong swap64(ulong x) {
  x = ((x & 0x00ff00ff00ff00ffUL) << 8) | ((x >> 8) & 0x00ff00ff00ff00ffUL);
  x = ((x & 0x0000ffff0000ffffUL) << 16) | ((x >> 16) & 0x0000ffff0000ffffUL);
  return (x << 32) | (x >> 32);
}

struct Params {
  ulong base[25];
  ulong thr;
  ulong start;
  uint iters;
};
struct Hits {
  atomic_uint count;
  uint padding;
  ulong nonces[64];
  ulong tops[64];
};

kernel void mine(constant Params &p [[buffer(0)]], device Hits &hits [[buffer(1)]],
                 uint tid [[thread_position_in_grid]], uint stride [[threads_per_grid]]) {
  ulong nonce = p.start + ulong(tid);
  for (uint it = 0; it < p.iters; it++, nonce += ulong(stride)) {
    KECCAK_VARS;
    KECCAK_LOAD(p.base);
    a6 ^= swap64(nonce);
    KECCAK_F_VARS();
    ulong top = swap64(a0);
    if (top < p.thr) {
      uint index = atomic_fetch_add_explicit(&hits.count, 1u, memory_order_relaxed);
      if (index < 64) {
        hits.nonces[index] = nonce;
        hits.tops[index] = top;
      }
    }
  }
}
)metal";
